"""Device-bound RP2040 firmware export, verified backup, install and undo.

Flashing runs in a separate process. No shell commands or automatic downloads.
All backups stay in the user's local FretGlow data directory.
"""
from pathlib import Path
import ctypes
import hashlib
import json
import os
import struct
import subprocess
import sys
import time
import uuid

import brotli
import libusb_package
import usb.core
import usb.util
import onboard

FLASH=0x10000000
END=FLASH+2*1024*1024
EEPROM=END-4096
FAMILY=0xE48BFF56
MAGIC=(0x0A324655,0x9E5D5157)
ASSETS=Path(__file__).resolve().parent/'firmware_assets'
NO_WINDOW=getattr(subprocess,'CREATE_NO_WINDOW',0)

def digest(data): return hashlib.sha256(data).hexdigest()

def write_json(path,data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    temp=path.with_suffix('.tmp')
    with temp.open('w',encoding='utf-8') as stream:
        json.dump(data,stream,indent=2); stream.flush(); os.fsync(stream.fileno())
    temp.replace(path)

def read_json(path): return json.loads(Path(path).read_text(encoding='utf-8'))

def process_running(pid):
    if os.name!='nt': return True
    kernel=ctypes.WinDLL('kernel32',use_last_error=True)
    kernel.OpenProcess.argtypes=[ctypes.c_uint32,ctypes.c_int,ctypes.c_uint32]
    kernel.OpenProcess.restype=ctypes.c_void_p
    kernel.GetExitCodeProcess.argtypes=[ctypes.c_void_p,ctypes.POINTER(ctypes.c_uint32)]
    kernel.CloseHandle.argtypes=[ctypes.c_void_p]
    handle=kernel.OpenProcess(0x1000,False,pid)
    if not handle: return ctypes.get_last_error()==5 # Access denied is not proof of exit.
    try:
        code=ctypes.c_uint32()
        return not kernel.GetExitCodeProcess(handle,ctypes.byref(code)) or code.value==259
    finally: kernel.CloseHandle(handle)

def parse_uf2(data,full=False):
    if not data or len(data)%512 or len(data)>4*1024*1024:
        raise ValueError('Invalid or incomplete UF2 file')
    total=len(data)//512; blocks={}; numbers=set()
    for offset in range(0,len(data),512):
        h=struct.unpack_from('<8I',data,offset)
        if h[:2]!=MAGIC or h[2]!=0x2000 or h[4]!=256 or h[6]!=total or h[7]!=FAMILY or struct.unpack_from('<I',data,offset+508)[0]!=0x0AB16F30:
            raise ValueError('Unsupported UF2 block')
        address=h[3]
        if not FLASH<=address<END or address%256 or h[5]>=total or h[5] in numbers or address in blocks:
            raise ValueError('Invalid or duplicate flash address')
        numbers.add(h[5]); blocks[address]=data[offset+32:offset+288]
    if full and set(blocks)!=set(range(FLASH,END,256)):
        raise ValueError('Backup is not a complete 2 MB flash image')
    return blocks

def make_uf2(blocks):
    result=bytearray()
    for i,(address,payload) in enumerate(sorted(blocks.items())):
        if len(payload)!=256: raise ValueError('Invalid flash block size')
        result+=struct.pack('<8I',*MAGIC,0x2000,address,256,i,len(blocks),FAMILY)
        result+=payload+bytes(220)+struct.pack('<I',0x0AB16F30)
    data=bytes(result); parse_uf2(data); return data

def template(assets=ASSETS):
    manifest=read_json(assets/'manifest.json')
    raw=(assets/'base.uf2').read_bytes()
    if digest(raw)!=manifest['template_sha256']: raise ValueError('The bundled firmware failed its integrity check')
    blocks=parse_uf2(raw)
    if min(blocks)!=FLASH or max(blocks)>=EEPROM: raise ValueError('Invalid firmware template')
    return manifest,blocks

def check_tool(assets,manifest):
    path=assets/'picotool.exe'
    if not path.is_file() or digest(path.read_bytes())!=manifest['picotool_sha256']:
        raise RuntimeError('The bundled recovery tool is missing or damaged. Extract the complete FretGlow ZIP again.')

def build_image(settings,base,backup=None):
    onboard.validate(settings)
    blocks=dict(base)
    if backup is None: sector=bytearray(b'\xff'*4096); sector[0]=1
    else:
        old=parse_uf2(backup,full=True)
        sector=bytearray(b''.join(old[a] for a in range(EEPROM,END,256)))
    sector[64:128]=settings
    for i in range(0,4096,256): blocks[EEPROM+i]=bytes(sector[i:i+256])
    return make_uf2(blocks)

def image_settings(raw,base):
    blocks=parse_uf2(raw)
    if set(blocks)!=set(base)|set(range(EEPROM,END,256)) or any(blocks[a]!=b for a,b in base.items()):
        raise ValueError('Choose firmware generated by this version of FretGlow for this guitar')
    return onboard.validate(blocks[EEPROM][64:128])

class DeviceIO:
    def __init__(self,assets,jobdir):
        self.tool=assets/'picotool.exe'; self.jobdir=jobdir; self.selector=[]
    def normal(self,boot=False):
        devices=list(usb.core.find(find_all=True,idVendor=0x1209,idProduct=0x2882,backend=libusb_package.get_libusb1_backend()))
        if len(devices)!=1: raise RuntimeError('Connect one guitar in controller mode. Hold Select for 5 seconds to leave keyboard mode.')
        d=devices[0]
        try:
            interfaces=[i.bInterfaceNumber for i in d[0] if (i.bInterfaceClass,i.bInterfaceSubClass,i.bInterfaceProtocol)==(255,93,2)]
            if interfaces!=[2]: raise RuntimeError('Return the guitar to its Windows controller mode first.')
            usb.util.claim_interface(d,2)
            board=bytes(d.ctrl_transfer(0xa1,0x36,0,2,64,timeout=700)).rstrip(b'\0')
            if board!=b'pico': raise RuntimeError('This updater supports the configured RP2040 Pico guitar only.')
            # XInput's device descriptor can omit iSerialNumber. Santroller's
            # read-serial command returns the actual Pico flash unique ID.
            device_id=bytes(d.ctrl_transfer(0xa1,0x43,0,2,20,timeout=700))[:16].decode('ascii').upper()
            if len(device_id)!=16 or any(c not in '0123456789ABCDEF' for c in device_id): raise RuntimeError('Could not identify this guitar safely.')
            config=bytearray()
            for offset in range(0,65536,64):
                part=bytes(d.ctrl_transfer(0xa1,0x34,offset,2,64,timeout=700)); config+=part
                if len(part)<64: break
            else: raise RuntimeError('Invalid guitar configuration')
            result=dict(device_id=device_id,config_sha256=digest(brotli.decompress(config)))
            if boot:
                try: d.ctrl_transfer(0x21,0x31,0,2,b'',timeout=700)
                except usb.core.USBError: pass # The USB reset can interrupt its own acknowledgement.
            return result
        finally: usb.util.dispose_resources(d)
    def command(self,*args,timeout=90):
        proc=subprocess.run([str(self.tool),*map(str,args),*self.selector],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,creationflags=NO_WINDOW,timeout=timeout)
        output=proc.stdout.decode('utf-8','replace')
        with (self.jobdir/'transfer.log').open('a',encoding='utf-8') as log:
            log.write('\n'+str(args[0])+'\n'+output)
        if proc.returncode: raise RuntimeError(output.strip()[-1500:] or 'Pico transfer failed')
        return output
    def recovery(self,device_id):
        deadline=time.monotonic()+12
        while time.monotonic()<deadline:
            devs=list(usb.core.find(find_all=True,idVendor=0x2e8a,idProduct=3,backend=libusb_package.get_libusb1_backend()))
            if len(devs)>1: raise RuntimeError('Disconnect other Pico boards before updating this guitar.')
            if len(devs)==1:
                # The ROM is composite: reading its string through the mass
                # storage interface can fail on Windows. picotool opens the
                # WinUSB interface; bus/address selects that same USB device.
                bus,address=devs[0].bus,devs[0].address
                if bus is None or address is None: raise RuntimeError('Cannot identify the recovery device.')
                self.selector=['--bus',str(bus),'--address',str(address)]
                info=self.command('info','-a',timeout=12)
                if device_id not in info.upper() or '2048K' not in info:
                    raise RuntimeError('Recovery device does not match the guitar or its 2 MB flash size.')
                return
            time.sleep(.2)
        raise RuntimeError('Pico recovery did not connect. Check USB and the RP2 Boot Interface 1 WinUSB driver.')
    def return_normal(self,device_id,settings=None):
        deadline=time.monotonic()+15; last=None
        while time.monotonic()<deadline:
            try:
                got=self.normal()
                if got['device_id']!=device_id: raise RuntimeError('A different guitar reconnected.')
                if settings is not None:
                    d=usb.core.find(idVendor=0x1209,idProduct=0x2882,backend=libusb_package.get_libusb1_backend())
                    try:
                        usb.util.claim_interface(d,2); status=onboard.info(d,2)
                        actual=bytes(d.ctrl_transfer(0xa1,0x71,0,2,64,timeout=700))
                        if not status[5]&8 or actual!=settings: raise RuntimeError('Firmware settings were not confirmed after restart.')
                    finally: usb.util.dispose_resources(d)
                return
            except Exception as error: last=error; time.sleep(.3)
        raise RuntimeError(f'The guitar did not reconnect correctly: {last}')

class FirmwareManager:
    def __init__(self,root,assets=ASSETS): self.root=Path(root); self.assets=Path(assets)
    def history(self):
        try: return read_json(self.root/'history.json')
        except FileNotFoundError: return []
    def restore_point(self):
        return next((r for r in reversed(self.history()) if r.get('action')=='install' and not r.get('undone') and r.get('backup_verified')),None)
    def generate(self,settings,path):
        _,base=template(self.assets); image=build_image(settings,base)
        path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
        temp=path.with_suffix('.tmp'); temp.write_bytes(image); temp.replace(path)
        return path
    def prepare(self,action,image=None):
        if action not in ('install','undo'): raise ValueError('Unknown firmware action')
        manifest,base=template(self.assets)
        check_tool(self.assets,manifest)
        restore=self.restore_point() if action=='undo' else None
        if action=='undo':
            if not restore: raise RuntimeError('There is no earlier firmware backup to restore yet.')
            backup=Path(restore['backup']).read_bytes(); parse_uf2(backup,full=True)
            if digest(backup)!=restore['backup_sha256']: raise ValueError('The recovery backup failed its integrity check')
        else: image_settings(Path(image).read_bytes(),base)
        folder=self.root/'jobs'/uuid.uuid4().hex; folder.mkdir(parents=True)
        if action=='install':
            (folder/'requested.uf2').write_bytes(Path(image).read_bytes()); image=folder/'requested.uf2'
        job=dict(action=action,image=str(image) if image else None,restore=restore,root=str(self.root.resolve()),assets=str(self.assets.resolve()))
        write_json(folder/'job.json',job)
        return folder/'job.json'
    def start(self,job):
        if getattr(sys,'frozen',False): command=[sys.executable,'--firmware-job',str(job)]
        else: command=[sys.executable,str(Path(__file__).with_name('fretglow.py')),'--firmware-job',str(job)]
        with Path(job).with_name('worker.log').open('ab') as log:
            proc=subprocess.Popen(command,stdin=subprocess.DEVNULL,stdout=log,stderr=log,creationflags=NO_WINDOW|getattr(subprocess,'CREATE_NEW_PROCESS_GROUP',0),close_fds=True)
        write_json(Path(job).with_name('process.json'),dict(pid=proc.pid))
    @staticmethod
    def state(job):
        path=Path(job).with_name('state.json')
        try: state=read_json(path)
        except FileNotFoundError: state=dict(status='running',message='Starting firmware helper…')
        process_file=Path(job).with_name('process.json')
        if state['status']=='running' and process_file.exists() and not process_running(read_json(process_file)['pid']):
            # Re-read: a worker can write its result just before exiting.
            if path.exists(): state=read_json(path)
            if state['status']=='running':
                state=dict(status='failed',message='The firmware helper stopped unexpectedly. Open backups to recover, or use Undo if a verified backup was saved.')
        return state

def execute_job(jobpath,io=None):
    jobpath=Path(jobpath); folder=jobpath.parent; job=read_json(jobpath)
    manager=FirmwareManager(job['root'],job['assets']); io=io or DeviceIO(manager.assets,folder)
    def progress(message,**kwargs): write_json(folder/'state.json',dict(status='running',message=message,**kwargs))
    manifest,base=template(manager.assets)
    check_tool(manager.assets,manifest)
    settings=image_settings(Path(job['image']).read_bytes(),base) if job['action']=='install' else None
    restore=job.get('restore')
    if restore:
        raw=Path(restore['backup']).read_bytes(); parse_uf2(raw,full=True)
        if digest(raw)!=restore['backup_sha256']: raise ValueError('Undo backup checksum failed')
        target=folder/'undo.uf2'; target.write_bytes(raw)
    progress('Checking guitar…')
    already_recovery=False
    try: normal=io.normal()
    except Exception:
        if not restore: raise
        io.recovery(restore['device_id']); already_recovery=True
        normal=dict(device_id=restore['device_id'])
    device_id=normal['device_id']
    if restore and device_id!=restore['device_id']: raise RuntimeError('This backup belongs to a different guitar.')
    if not restore and normal['config_sha256'] not in manifest['compatible_config_sha256']:
        raise RuntimeError('This firmware was built for a different guitar configuration. Nothing was changed.')
    progress('Entering recovery mode…')
    if not already_recovery: io.normal(boot=True)
    wrote=False; backed_up=False; record=None; recovery_confirmed=False
    try:
        io.recovery(device_id)
        recovery_confirmed=True
        progress('Backing up and verifying current firmware…')
        backup=folder/'before.uf2'; io.command('save','-a','-v',backup)
        old=backup.read_bytes(); parse_uf2(old,full=True); backed_up=True
        record=dict(id=folder.name,action=job['action'],device_id=device_id,backup=str(backup),backup_sha256=digest(old),backup_verified=True,undone=False,status='prepared')
        history=manager.history(); history.append(record); write_json(manager.root/'history.json',history)
        if settings is not None:
            target=folder/'install.uf2'; target.write_bytes(build_image(settings,base,old))
        progress('Installing and verifying firmware. Keep USB connected.',backup=str(backup))
        wrote=True
        io.command('load','-v',target)
        progress('Restarting guitar…',backup=str(backup))
        io.command('reboot')
        io.return_normal(device_id,settings)
        record['status']='complete'
        if restore:
            for item in history:
                if item['id']==restore['id']: item['undone']=True
        write_json(manager.root/'history.json',history)
        message='Previous firmware restored.' if restore else 'Firmware installed. Your settings are saved on the guitar.'
        write_json(folder/'state.json',dict(status='complete',message=message,backup=str(backup)))
    except Exception as error:
        recovered=False
        if wrote and backed_up:
            progress('Update failed. Restoring the verified backup…',backup=str(backup))
            try:
                try: io.normal(boot=True)
                except Exception: pass # It may already be in recovery mode.
                io.recovery(device_id)
                io.command('load','-v',backup); io.command('reboot'); io.return_normal(device_id)
                recovered=True
                record['status']='rolled_back'; record['undone']=True
                write_json(manager.root/'history.json',history)
            except Exception as recovery_error:
                error=RuntimeError(f'{error}\nAutomatic restore could not finish: {recovery_error}\nManual recovery file: {backup}')
        elif not wrote and recovery_confirmed:
            try: io.command('reboot')
            except Exception: pass
        message=str(error)+ (' Previous firmware was restored.' if recovered else '')
        write_json(folder/'state.json',dict(status='failed',message=message,backup=str(backup) if backed_up else None))

def run_worker(jobpath):
    # Independent process: app exit or a chat interruption does not cancel a transfer.
    handle=None
    try:
        if os.name=='nt':
            kernel=ctypes.WinDLL('kernel32',use_last_error=True)
            kernel.CreateMutexW.argtypes=[ctypes.c_void_p,ctypes.c_int,ctypes.c_wchar_p]
            kernel.CreateMutexW.restype=ctypes.c_void_p
            handle=kernel.CreateMutexW(None,False,'Local\\FretGlowFirmwareTransfer')
            if not handle: raise RuntimeError('Could not lock firmware access. Please restart the app.')
            if ctypes.get_last_error()==183: raise RuntimeError('Another firmware transfer is already running.')
        execute_job(jobpath)
    except Exception as error:
        write_json(Path(jobpath).with_name('state.json'),dict(status='failed',message=str(error)))
    finally:
        if handle:
            kernel.CloseHandle.argtypes=[ctypes.c_void_p]; kernel.CloseHandle(handle)
